name: "yolov5tensorrt"
platform: "tensorrt_plan"
default_model_filename: "yolov5s.engine"
max_batch_size: 1
input: [
    {
        name: "images"
        data_type: TYPE_FP32
        format: FORMAT_NONE
        dims: [ 3, 640, 640 ]
    }
]
output: [
    {
        name: "344",
        data_type: TYPE_FP32
        dims: [ 3,80,80,85 ]
    },
    {
        name: "404",
        data_type: TYPE_FP32
        dims: [ 3,40,40,85 ]
    },
    {
        name: "464",
        data_type: TYPE_FP32
        dims: [ 3,20,20,85 ]
    },
    {
        name: "output",
        data_type: TYPE_FP32
        dims: [ 25200,85 ]
    }
]
instance_group: [
    {
        name: "yolov5tensorrt"
        kind: KIND_GPU
        count: 2
        gpus: [ 0 ]
    }
]
